# Site settings
title: Cheerful
header-img: "img/Spring.jpg"
tagline: "悠闲"  
description: "捡一片慵懒，慢悠生活"  
baseurl: ""
#url: "http://azeril.me"  
#url: "http://localhost:4000"

# About/contact
owner: 
  name: "cheerannie"
  email: cheerannie@163.com
  bio: "明朝即長路 惜取此時心"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.ico

# douban_username: Azeril
# twitter_username: Azeril_Lapland  
# github_username: Azeril  
# facebook_username: Azeril_Lapland  
# weibo_username: Azeril  
# zhihu_username: Azeril  

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

gems: 
- jekyll-gallery-generator
- jekyll-paginate
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Beijing

# Title


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "cheerannie"
      header-img: "img/fantasy.jpg" # We don't want posts without a header image, that whould mean white on white


# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : cheerannie
  disqus :
      short_name : cheerannie

# Analytics and webmaster tools stuff goes here
# google_analytics: UA-66863061-1
# google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify:

# Links to include in footer navigation
